// client/vue/src/components/user-list.vue
<script setup>
import { socket } from "../socket";
import { usersListStore } from "../stores/users-list-store.ts";

socket.on("user list", (data) => {
  usersListStore.updateUsersList(Object.values(data.users));
});
</script>

<template>
  <div
    class="flex flex-col w-full min-h-12 justify-center px-3 py-1 mt-4 bg-slate-400 rounded-md"
  >
    <h3>Users List</h3>
    <p v-if="usersListStore.isEmpty()">The chat-room is empty!</p>
    <p v-if="!usersListStore.isEmpty()" class="capitalize text-sm">
      {{ usersListStore.visibleUsersList() }}
    </p>
  </div>
</template>

// client/react/src/user-list/user-list.tsx
import { useEffect, useState } from "react";
import { socket } from "../utils/socket";

type User = {
  name: string;
  room: string;
  id: string;
};

export function UserList() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    socket.on("user list", (data) => {
      const updateUsersArray = Object.values(data.users) as User[];
      setUsers(updateUsersArray);
    });
  });

  const visibleUsers = users.map((user) => user.name).join(", ");

  return (
    <div className="flex flex-col w-full min-h-12 justify-center px-3 py-1 mt-4 bg-slate-400 rounded-md">
      <h3>Users List</h3>
      {users.length === 0 ? (
        <p>The chat-room is empty!</p>
      ) : (
        <p className="capitalize text-sm">{visibleUsers}</p>
      )}
    </div>
  );
}
