// client/vue/src/App.vue
<script setup lang="ts">
import JoinForm from "./components/join-form.vue";
import MessageList from "./components/message-list.vue";
import UserList from "./components/user-list.vue";
import CreateMessage from "./components/create-message.vue";
</script>

<template>
  <div class="flex flex-col p-4 h-screen">
    <JoinForm />
    <MessageList />
    <UserList />
    <CreateMessage />
  </div>
</template>

// client/react/src/App.tsx
import { CreateMessage } from "./create-message/create-message";
import { JoinForm } from "./join-form/join-form";
import { MessageList } from "./messages/message-list";
import { UserList } from "./user-list/user-list";

function App() {
  return (
    <div className="flex flex-col p-4 h-screen">
      <JoinForm />
      <MessageList />
      <UserList />
      <CreateMessage />
    </div>
  );
}

export default App;
