// client/react/src/messages/message.tsx
import { format } from "date-fns";

import type { MessageType } from "./types";
import { useUserName } from "../hooks/use-user-name";

const ADMIN = "Admin";

type MessageProps = {
  message: MessageType;
};

export function Message({ message }: MessageProps) {
  const { userName } = useUserName();

  let postLocation = "";
  let headerBgStyle = "";
  if (message.username !== ADMIN) {
    if (message.username === userName) {
      postLocation = "self-start w-[60%]";
      headerBgStyle = "bg-blue-600";
    } else {
      postLocation = "self-end w-[60%]";
      headerBgStyle = "bg-purple-600";
    }
  }

  return (
    <div
      className={`border rounded-md m-4 bg-slate-300 overflow-hidden flex-shrink ${postLocation}`}
    >
      {message.username !== ADMIN && (
        <div
          className={`flex justify-between p-1 rounded-top-md ${headerBgStyle}`}
        >
          <p className="justify-center items-center capitalize font-semibold">
            {message.username}
          </p>
          <p className="justify-center items-center text-s">
            {format(message.createAt, "H:mm:ss")}
          </p>
        </div>
      )}
      <div className="mt-1 px-1 py-2">{message.content}</div>
    </div>
  );
}

// client/vue/src/components/message.vue
<script setup>
import { format } from "date-fns";
import { userStore } from "../stores/user-store.ts";

defineProps({
  username: String,
  content: String,
  createAt: Number,
});

const ADMIN = "Admin";
const currentUsername = userStore.userName;
</script>

<template>
  <div
    :class="{
      'border rounded-md m-4 bg-slate-300 overflow-hidden flex-shrink': true,
      'self-start w-[60%]': username !== ADMIN && username === currentUsername,
      'self-end w-[60%]': username !== ADMIN && username !== currentUsername,
    }"
  >
    <div
      v-if="username !== ADMIN"
      :class="{
        'flex justify-between p-1 rounded-top-md': true,
        'bg-blue-600': username === currentUsername,
        'bg-blue-600': username !== currentUsername,
      }"
    >
      <p class="justify-center items-center capitalize font-semibold">
        {{ username }}
      </p>
      <p className="justify-center items-center text-s">
        {{ format(createAt, "H:mm:ss") }}
      </p>
    </div>
    <div
      :class="{
        'mt-1 px-1 py-2': true,
        'flex justify-center': username === ADMIN,
      }"
    >
      {{ content }}
    </div>
  </div>
</template>
