// client/react/src/messages/message-list.tsx
import { useState } from "react";

import { Message } from "./message";
import type { MessageType } from "./types";
import { socket } from "../utils/socket";

export function MessageList() {
  const [messages, setMessages] = useState<MessageType[]>([]);

  socket.on("message", (data: MessageType) => {
    const updateMessageList = [...messages, data];
    setMessages(updateMessageList);
  });

  return (
    <div className="flex flex-col h-screen overflow-auto">
      <div className="flex-grow bg-slate-200 w-full rounded-xl justify-start mx-auto">
        {messages.map((message) => (
          <Message key={message.createAt} message={message} />
        ))}
      </div>
    </div>
  );
}

// client/vue/src/components/message-list.vue
<script setup>
import Message from "./message.vue";
import { socket } from "../socket";
import { messageStore } from "../stores/message-store.ts";

socket.on("message", (data) => {
  messageStore.updateMessages(data);
});
</script>

<template>
  <div class="flex flex-col h-screen overflow-auto">
    <div class="flex-grow bg-slate-200 w-full rounded-xl justify-start mx-auto">
      <Message
        v-for="message in messageStore.messages"
        :username="message.username"
        :content="message.content"
        :createAt="message.createAt"
      />
    </div>
  </div>
</template>
